urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView

from . import views

app_name='orthomodoweb'

urlpatterns = [
    #home page
    url(r'^$',views.HomeView.as_view(),name='home'),
    
    #About/Help page
    url(r'^guide/$',views.UserGuide.as_view(),name='userguide'),    
       
    #export
    url(r'^export_as_csv/$',views.export_as_csv,name='export_as_csv'),
    
    #orthomodojob
    url(r'^orthomodojob/open/$', views.OrthoModoJobViewOpen.as_view(), name='orthomodojob-open-list'),
    url(r'^orthomodojob/all/$', views.OrthoModoJobViewAll.as_view(), name='orthomodojob-all-list'),
    url(r'^orthomodojob/add/$', views.OrthoModoJobCreate.as_view(), name='orthomodojob-add'),
    url(r'^orthomodojob/(?P<pk>[0-9]+)/$', views.OrthoModoJobUpdate.as_view(), name='orthomodojob-update'),
    url(r'^orthomodojob/(?P<pk>[0-9]+)/delete$', views.OrthoModoJobDelete.as_view(), name='orthomodojob-delete'),
       
    #login/logout/signup
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'orthomodoweb:home'}, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^admin/', admin.site.urls),
    
    #printers
    url(r'^printer/$', views.PrinterView.as_view(), name='printer-list'),
    url(r'^printer/add/$', views.PrinterCreate.as_view(), name='printer-add'),
    url(r'^printer/(?P<pk>[0-9]+)/$', views.PrinterUpdate.as_view(), name='printer-update'),
    url(r'^printer/(?P<pk>[0-9]+)/delete$', views.PrinterDelete.as_view(), name='printer-delete'),
    
    #patients
    url(r'^patient/$', views.PatientView.as_view(), name='patient-list'),
    url(r'^patient/add/$', views.PatientCreate.as_view(), name='patient-add'),
    url(r'^patient/(?P<pk>[0-9]+)/$', views.PatientUpdate.as_view(), name='patient-update'),
    url(r'^patient/(?P<pk>[0-9]+)/delete$', views.PatientDelete.as_view(), name='patient-delete'),
    url(r'^patient/(?P<patient_id>[0-9]+)/addjob$', views.OrthoModoPatientJobCreate.as_view(), name='patient-add-job'),
    
    #clinicians
    url(r'^clinician/$', views.ClinicianView.as_view(), name='clinician-list'),
    url(r'^clinician/add/$', views.ClinicianCreate.as_view(), name='clinician-add'),
    url(r'^clinician/(?P<pk>[0-9]+)/$', views.ClinicianUpdate.as_view(), name='clinician-update'),
    url(r'^clinician/(?P<pk>[0-9]+)/delete$', views.ClinicianDelete.as_view(), name='clinician-delete'),
    
    #labitemtypes
    url(r'^labitemtype/$', views.LabItemTypeView.as_view(), name='labitemtype-list'),
    url(r'^labitemtype/add/$', views.LabItemTypeCreate.as_view(), name='labitemtype-add'),
    url(r'^labitemtype/(?P<pk>[0-9]+)/$', views.LabItemTypeUpdate.as_view(), name='labitemtype-update'),
    url(r'^labitemtype/(?P<pk>[0-9]+)/delete$', views.LabItemTypeDelete.as_view(), name='labitemtype-delete'),
    
     #collectiontype
    url(r'^collectiontype/$', views.CollectionTypeView.as_view(), name='collectiontype-list'),
    url(r'^collectiontype/add/$', views.CollectionTypeCreate.as_view(), name='collectiontype-add'),
    url(r'^collectiontype/(?P<pk>[0-9]+)/$', views.CollectionTypeUpdate.as_view(), name='collectiontype-update'),
    url(r'^collectiontype/(?P<pk>[0-9]+)/delete$', views.CollectionTypeDelete.as_view(), name='collectiontype-delete'),
    
    #labitems
     url(r'^(?P<orthomodojob_id>[0-9]+)/labitem/add/$', views.LabItemCreate.as_view(), name='labitem-create'),
     url(r'^(?P<orthomodojob_id>[0-9]+)/labitem/(?P<pk>[0-9]+)/$', views.LabItemUpdate.as_view(), name='labitem-update'),
     url(r'^orthomodojob/labitem/$', views.LabItemView.as_view(), name='labitem-list'),
     
     #redirect everything unknown to the home pahe
     #url(r'^.*$', RedirectView.as_view(pattern_name='home', permanent=False), name='index')
]

templates/orthomodoweb/base.html
{% load staticfiles %}
<html>
    <head>
        <title>OrthoModo Web: 3d model printing</title>       
        <link rel = "stylesheet" type = "text/css" href="{% static 'orthomodoweb/style.css' %}">
		<link rel = "stylesheet" type = "text/css" href="{% static 'orthomodoweb/jquery-ui.css' %}">
		<link rel = "stylesheet" type = "text/css" href="{% static 'orthomodoweb/font-awesome-4.7.0/css/font-awesome.css' %}">
		<script src ="{% static 'orthomodoweb/jquery-3.2.1.min.js' %}"></script>
		<script src ="{% static 'orthomodoweb/jquery-ui.js' %}"></script>
    </head>
	<body>
		<div class="page-header">
			<strong>OrthoModo Web</strong>
			<span class = "userinfo" > Logged in as {{ user.get_username }}	 | <a href="{% url 'orthomodoweb:logout' %}">Logout</a>	</span>				
			<div id = "topmenu">
			<ul>
			<li><a href="{% url 'orthomodoweb:home' %}">HOME</a></li>
			<li><a href="{% url 'orthomodoweb:patient-list' %}">PATIENTS</a></li>	
			<li><a href="{% url 'orthomodoweb:orthomodojob-open-list' %}">OPEN JOBS</a></li>			
			<li><a href="{% url 'orthomodoweb:orthomodojob-all-list' %}">ALL JOBS</a></li>						
			<li><a href="{% url 'orthomodoweb:labitem-list' %}">LAB ITEMS</a></li>
			<li><a href="{% url 'orthomodoweb:printer-list' %}">PRINTERS</a></li>
			<li><a href="{% url 'orthomodoweb:clinician-list' %}">CLINICIANS</a></li>
			<li><a href="{% url 'orthomodoweb:labitemtype-list' %}">LAB ITEM TYPES</a></li>
			<li><a href="{% url 'orthomodoweb:collectiontype-list' %}">COLLECTION TYPES</a></li>
			</ul>
			
		</div>			
		</div>
		<div class="content container">
			<div class="row">
				<div class="col-md-8">
				{% block content %}
				{% endblock %}
				</div>
			</div>
		</div>
		<div class="page-footer">
		OrthoModo Web System. Developed by Donakello. <span class='support_link'>Problems? EMAIL <a href="mailto:donakello@gmail.com?Subject=OrthoModo Web Support" target="_top">donakello@gmail.com</a></span>
		</div>
	</body>
</html>

templates/orthomodoweb/guide.html
{% extends 'orthomodoweb/base.html' %}
{% block content %}


<div class = "guidepage">

<h2>ORTHOMODO-WEB: Manage your Ortho Model Patients and Jobs.</h2>

<p>
<h4> <i class="fa fa-exclamation-triangle fa-3x" aria-hidden="true"></i> IMPORTANT NOTES </h4>

<i class="fa fa-calendar fa-3x" aria-hidden="true"></i> The date format used is YY-MM-DD. This means that December 1st, 2017 will show as 17-12-01. This date format is the easiest format for a database and cannot get confused between day and month, e.g. is 12/7 July 12th or December 7th?
<br /><br />
<i class="fa fa-floppy-o fa-3x" aria-hidden="true"></i> When you make a change, make sure you SAVE before moving to a different view!
<br /><br />
<i class="fa fa-refresh fa-3x" aria-hidden="true"></i> OrthoModo Web is like any website: Use the REFRESH and BACK buttons to make sure your data is correct or you need to move to the previous page.

</p>

<p>
<h4><i class="fa fa-database fa-3x" aria-hidden="true"></i> What is the Orthomodo Database system for?</h4> 
Orthomodoweb is a database system for storing basic information to track orthodontic jobs.
It's aim is to make it easy for many users to access and update information about the following
<ol>
<li><i class="fa-li fa fa-square"></i>Patient names, contact details, and Orthotrac system references, which can be easily searched</li>
<li><i class="fa-li fa fa-square"></i>Patient Scan dates and assigned Clinician</li>
<li><i class="fa-li fa fa-square"></i>Plaster Model and 3D Printed Model details</li>
<li><i class="fa-li fa fa-square"></i>Lab Items that are required, such as Retainers and Gumshields</li>
<li><i class="fa-li fa fa-square"></i>Planned Collection/Delivery type and dates </li>
</ol>

</p>
<p>
<h4><i class="fa fa-eye fa-3x" aria-hidden="true"></i> How do I use the system?</h4> 

The basic process when using the system to add patient/job/lab item details is the following
<ul>
<li><i class="fa-li fa fa-square"></i>Check if a patient already exists by searching the patient of jobs list</li>
<li><i class="fa-li fa fa-square"></i>Create a New patient if he/she is not already on the system. Use the Orthotrac reference number as the patient CODE</li>
<li><i class="fa-li fa fa-square"></i>Add a New JOB for that patient, or edit one of their existing jobs. A patient may have many separate jobs. A job is based on a printed 3D or plaster MODEL. If you are creating a new model, then create a new JOB</li>
<li><i class="fa-li fa fa-square"></i>An UNCOLLECTED and UNFLAGGED job is OPEN: it will show up in the OPEN list. This will make it easy to find jobs that are currently in progress</li>
<li><i class="fa-li fa fa-square"></i>As a JOB progresses, details must be updated, such as when a model was printed/moulded, when it is planned to be collected, etc</li>
<li><i class="fa-li fa fa-square"></i>Each JOB will have an assigned MODEL USE: this will define what is to be done with a model when created. For example, Lab Items such as a Gumshield may be needed, or the clinician may need to inspect the model, or it may need to be posted directly to a dentist or patient. This should be updated if the use changes.</li>
<li><i class="fa-li fa fa-square"></i>Lab Items may be added to each JOB. A Lab Item is something that is created using the Model, such as a Retainer or gumshield.</li>
<li><i class="fa-li fa fa-square"></i>Each Lab Item will have a Type (e.g. Gumshield LOWER) and a Material (e.g. Essix 0.5mm, or Gumshield Blue). The Date Made can be added, and the item can be confirmed as made "Is Made?"</li>
<li><i class="fa-li fa fa-square"></i>Each Lab Item will have a Type (e.g. Gumshield LOWER) and a Material (e.g. Essix 0.5mm, or Gumshield Blue). The Date Made can be added, and the item can be confirmed as made "Is Made?"</li>
<li><i class="fa-li fa fa-square"></i>In order to quickly display lab item info, a Lab Item Code will be created. This will look like the following: RU 05 B M 12-01. This code is a shorthand for Retainer Upper, 0.5mm Essix, Is Blocked, Is Made, Made on 2017/12/01</li>
</ul>

</p>

<p>
<h4><i class="fa fa-cogs fa-3x" aria-hidden="true"></i> Setting up the System</h4>
The system will need the following items to be added so that they can be selected for Jobs and Lab Items:
<ol>
<li><i class="fa-li fa fa-square"></i>Printers: 3D printers</li>
<li><i class="fa-li fa fa-square"></i>Clinicians</li>
<li><i class="fa-li fa fa-square"></i>Lab Item Types: Basic Lab Item type, such as Retainer Upper, Retainer Lower, Gumshield Upper, and Gumshield Lower.</li>
<li><i class="fa-li fa fa-square"></i>Created Model Uses*: WHat will the model be used for? Further Analysis? To create Lab Items?</li>
<li><i class="fa-li fa fa-square"></i>Lab Item Materials*: What material will a lab item such as a retainer, be created from?</li>
<li><i class="fa-li fa fa-square"></i>Model Types*: This is limited to two basic types of model: Plaster and 3D Print</li>

* These are currently only found in the ADMIN section, for which you will need to be an ADMIN user.

</ol>
</p>

<p><h4><i class="fa fa-file-excel-o fa-3x" aria-hidden="true"></i> CSV Export</h4>
On the HOME page, you will find an option that lets you download all of the system JOBS as a CSV file. This will include a line for each Lab Item if they exist, and can be opened in Microsoft Excel. You can use this to analyse the data or create a quick backup for reference.
</p>



</div>

{% endblock %}

templates/orthomodoweb/signup.html
{% block content %}
  <h2>Sign up to HeyDayzDiary</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}