urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView

from . import views

app_name='orthomodoweb'

urlpatterns = [
    #home page
    url(r'^$',views.HomeView.as_view(),name='home'),
    
    #About/Help page
    url(r'^guide/$',views.UserGuide.as_view(),name='userguide'),    
       
    #export
    url(r'^export_as_csv/$',views.export_as_csv,name='export_as_csv'),
    
    #orthomodojob
    url(r'^orthomodojob/open/$', views.OrthoModoJobViewOpen.as_view(), name='orthomodojob-open-list'),
    url(r'^orthomodojob/all/$', views.OrthoModoJobViewAll.as_view(), name='orthomodojob-all-list'),
    url(r'^orthomodojob/add/$', views.OrthoModoJobCreate.as_view(), name='orthomodojob-add'),
    url(r'^orthomodojob/(?P<pk>[0-9]+)/$', views.OrthoModoJobUpdate.as_view(), name='orthomodojob-update'),
    url(r'^orthomodojob/(?P<pk>[0-9]+)/delete$', views.OrthoModoJobDelete.as_view(), name='orthomodojob-delete'),
       
    #login/logout/signup
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'orthomodoweb:home'}, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^admin/', admin.site.urls),
    
    #printers
    url(r'^printer/$', views.PrinterView.as_view(), name='printer-list'),
    url(r'^printer/add/$', views.PrinterCreate.as_view(), name='printer-add'),
    url(r'^printer/(?P<pk>[0-9]+)/$', views.PrinterUpdate.as_view(), name='printer-update'),
    url(r'^printer/(?P<pk>[0-9]+)/delete$', views.PrinterDelete.as_view(), name='printer-delete'),
    
    #patients
    url(r'^patient/$', views.PatientView.as_view(), name='patient-list'),
    url(r'^patient/add/$', views.PatientCreate.as_view(), name='patient-add'),
    url(r'^patient/(?P<pk>[0-9]+)/$', views.PatientUpdate.as_view(), name='patient-update'),
    url(r'^patient/(?P<pk>[0-9]+)/delete$', views.PatientDelete.as_view(), name='patient-delete'),
    url(r'^patient/(?P<patient_id>[0-9]+)/addjob$', views.OrthoModoPatientJobCreate.as_view(), name='patient-add-job'),
    
    #clinicians
    url(r'^clinician/$', views.ClinicianView.as_view(), name='clinician-list'),
    url(r'^clinician/add/$', views.ClinicianCreate.as_view(), name='clinician-add'),
    url(r'^clinician/(?P<pk>[0-9]+)/$', views.ClinicianUpdate.as_view(), name='clinician-update'),
    url(r'^clinician/(?P<pk>[0-9]+)/delete$', views.ClinicianDelete.as_view(), name='clinician-delete'),
    
    #labitemtypes
    url(r'^labitemtype/$', views.LabItemTypeView.as_view(), name='labitemtype-list'),
    url(r'^labitemtype/add/$', views.LabItemTypeCreate.as_view(), name='labitemtype-add'),
    url(r'^labitemtype/(?P<pk>[0-9]+)/$', views.LabItemTypeUpdate.as_view(), name='labitemtype-update'),
    url(r'^labitemtype/(?P<pk>[0-9]+)/delete$', views.LabItemTypeDelete.as_view(), name='labitemtype-delete'),
    
     #collectiontype
    url(r'^collectiontype/$', views.CollectionTypeView.as_view(), name='collectiontype-list'),
    url(r'^collectiontype/add/$', views.CollectionTypeCreate.as_view(), name='collectiontype-add'),
    url(r'^collectiontype/(?P<pk>[0-9]+)/$', views.CollectionTypeUpdate.as_view(), name='collectiontype-update'),
    url(r'^collectiontype/(?P<pk>[0-9]+)/delete$', views.CollectionTypeDelete.as_view(), name='collectiontype-delete'),
    
    #labitems
     url(r'^(?P<orthomodojob_id>[0-9]+)/labitem/add/$', views.LabItemCreate.as_view(), name='labitem-create'),
     url(r'^(?P<orthomodojob_id>[0-9]+)/labitem/(?P<pk>[0-9]+)/$', views.LabItemUpdate.as_view(), name='labitem-update'),
     url(r'^orthomodojob/labitem/$', views.LabItemView.as_view(), name='labitem-list'),
     
     #redirect everything unknown to the home pahe
     #url(r'^.*$', RedirectView.as_view(pattern_name='home', permanent=False), name='index')
]

models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

class Printer(models.Model):
    name = models.CharField(max_length=200)
    code = models.CharField(max_length=10)
    description = models.TextField(blank=True)
    date_updated = models.DateTimeField('Date updated',auto_now=True)
    date_created = models.DateTimeField('Date Created',auto_now_add=True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
       return reverse('orthomodoweb:printer-update', kwargs={'pk': self.pk})

class Patient(models.Model):
    name = models.CharField(max_length=200)
    code = models.CharField(max_length=20,unique=True)
    reference_no = models.CharField(max_length=50,blank=True)
    description = models.TextField(blank=True)
    email = models.EmailField(blank=True)
    phone_no_1 = models.CharField(blank=True,max_length=50)
    phone_no_2 = models.CharField(blank=True,max_length=50)
    address = models.CharField(blank=True,max_length=300)
    dob = models.DateField(blank=True, null=True)
    date_updated = models.DateTimeField('Date updated',auto_now=True)
    date_created = models.DateTimeField('Date Created',auto_now_add=True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
       return reverse('orthomodoweb:patient-update', kwargs={'pk': self.pk})
       
class Clinician(models.Model):
    name = models.CharField(max_length=200)
    code = models.CharField(max_length=20,unique=True)
    description = models.TextField(blank=True)
    date_updated = models.DateTimeField('Date updated',auto_now=True)
    date_created = models.DateTimeField('Date Created',auto_now_add=True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
       return reverse('orthomodoweb:clinician-update', kwargs={'pk': self.pk})
       
class LabItemType(models.Model):
    code = models.CharField(max_length=20,unique=True)
    name = models.CharField(max_length=200)    
    description = models.TextField(blank=True)
    date_updated = models.DateTimeField('Date updated',auto_now=True)
    date_created = models.DateTimeField('Date Created',auto_now_add=True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
       return reverse('orthomodoweb:labitemtype-update', kwargs={'pk': self.pk})

class LabItemMaterial(models.Model):
    code = models.CharField(max_length=20,unique=True)
    name = models.CharField(max_length=200)    
    description = models.TextField(blank=True)
    date_updated = models.DateTimeField('Date updated',auto_now=True)
    date_created = models.DateTimeField('Date Created',auto_now_add=True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
       return reverse('orthomodoweb:labitemmaterial-update', kwargs={'pk': self.pk})
       
       
class CollectionType(models.Model):    
    code = models.CharField(max_length=20,unique=True)
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    date_updated = models.DateTimeField('Date updated',auto_now=True)
    date_created = models.DateTimeField('Date Created',auto_now_add=True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
       return reverse('orthomodoweb:collectiontype-update', kwargs={'pk': self.pk})

class ModelType(models.Model):     
    name = models.CharField(max_length=30, unique=True)
    def __str__(self):
        return self.name
        
class CreatedModelUse(models.Model):     
    code = models.CharField(max_length=20, unique=True)
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name
 
class OrthoModoJob(models.Model):      
    patient = models.ForeignKey(Patient, on_delete=models.PROTECT)
    clinician = models.ForeignKey(Clinician, on_delete=models.PROTECT)
    model_type = models.ForeignKey(ModelType, on_delete=models.PROTECT)
    scan_date = models.DateField(blank=True, null=True)    
    scan_date_entered_by = models.ForeignKey(settings.AUTH_USER_MODEL,blank=True,null=True,related_name="orthomodojob_scan_date_entered_by")
    scan_date_entered_when = models.DateTimeField(blank=True, null=True)    
    orthotrac_analysis_done = models.BooleanField(default=False)
    orthotrac_analysis_notes = models.TextField(blank=True)    
    printer = models.ForeignKey(Printer, on_delete=models.PROTECT,blank=True,null=True)
    is_stl_file_prepared = models.BooleanField(default=False)
    stl_marked_as_prepared_by = models.ForeignKey(settings.AUTH_USER_MODEL,blank=True,null=True,related_name="orthomodojob_stl_marked_as_prepared_by")
    stl_marked_as_prepared_when = models.DateTimeField(blank=True, null=True)    
    is_printed = models.BooleanField(default=False)
    print_date = models.DateField(blank=True, null=True)   
    is_printed_marked_by = models.ForeignKey(settings.AUTH_USER_MODEL,blank=True,null=True,related_name="orthomodojob_is_printed_marked_by")
    is_printed_marked_when = models.DateTimeField(blank=True, null=True)  
    is_poured =  models.BooleanField(default=False)
    poured_date = models.DateField(blank=True, null=True)   
    is_poured_marked_by = models.ForeignKey(settings.AUTH_USER_MODEL,blank=True,null=True,related_name="orthomodojob_is_poured_marked_by")
    is_poured_marked_when = models.DateTimeField(blank=True, null=True) 
    created_model_use = models.ForeignKey(CreatedModelUse, on_delete=models.PROTECT,blank=True,null=True)    
    collection_type = models.ForeignKey(CollectionType, on_delete=models.PROTECT,blank=True,null=True)
    planned_collection_date = models.DateField(blank=True, null=True)    
    planned_collection_time = models.TimeField(blank=True, null=True)
    collection_notes = models.TextField(blank=True)    
    is_collected = models.BooleanField(default=False)
    is_collected_marked_by = models.ForeignKey(settings.AUTH_USER_MODEL,blank=True,null=True,related_name="orthomodojob_is_collected_marked_by")
    is_collected_marked_when = models.DateTimeField(blank=True, null=True)    
    flagged = models.BooleanField(default=False)
    flag_status_set_by = models.ForeignKey(settings.AUTH_USER_MODEL,blank=True,null=True,related_name="orthomodojob_flag_status_set_by")
    flag_status_set_when = models.DateTimeField(blank=True, null=True)
    flag_status_note = models.TextField(blank=True)
    last_updated_by = models.ForeignKey(settings.AUTH_USER_MODEL,blank=True,null=True,related_name="orthomodojob_last_updated_by")
    date_updated = models.DateTimeField('Date updated',auto_now=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL,blank=True,null=True,related_name="orthomodojob_created_by")
    date_created = models.DateTimeField('Date Created',auto_now_add=True)
    def __str__(self):
        return str(self.id)
    def get_absolute_url(self):
       return reverse('orthomodoweb:orthomodojob-update', kwargs={'pk': self.pk})
   
class LabItem(models.Model):
    orthomodojob = models.ForeignKey(OrthoModoJob, on_delete=models.PROTECT)
    lab_item_type = models.ForeignKey(LabItemType, on_delete=models.PROTECT)
    lab_item_material = models.ForeignKey(LabItemMaterial, on_delete=models.PROTECT)
    is_blocked =  models.BooleanField(default=False)
    is_made =  models.BooleanField(default=False)
    made_date = models.DateTimeField(blank=True, null=True)  
    is_made_marked_by = models.ForeignKey(settings.AUTH_USER_MODEL,blank=True,null=True,related_name="lab_item_is_made_marked_by")
    is_made_marked_when = models.DateTimeField(blank=True, null=True)     
    notes= models.TextField(blank=True)
    last_updated_by = models.ForeignKey(settings.AUTH_USER_MODEL,blank=True,null=True,related_name="lab_item_last_updated_by")
    date_updated = models.DateTimeField('Date updated',auto_now=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL,blank=True,null=True,related_name="lab_item_created_by")
    date_created = models.DateTimeField('Date Created',auto_now_add=True)
    def __str__(self):
        return self.lab_item_type.name
    def get_absolute_url(self):
       return reverse('orthomodoweb:orthomodojob-update', kwargs={'pk': self.orthomodojob.id})

forms.py
from django import forms
from .models import Printer
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class PrinterForm(forms.ModelForm):
    name = forms.CharField(label='Printer Name', max_length=200,widget=forms.TextInput(attrs={'class': "input-lg"}))
    code = forms.CharField(label='Printer Code', max_length=10,widget=forms.TextInput(attrs={'class': "input-lg"}))    
    description = forms.CharField(label='Printer Description')
    
class PatientForm(forms.ModelForm):
    name = forms.CharField(label='Printer Name', max_length=200,widget=forms.TextInput(attrs={'class': "input-lg"}))
    code = forms.CharField(label='Printer Code', max_length=10,widget=forms.TextInput(attrs={'class': "input-lg"}))    
    description = forms.CharField(label='Printer Description')
    
class ClinicianForm(forms.ModelForm):
    name = forms.CharField(label='Printer Name', max_length=200,widget=forms.TextInput(attrs={'class': "input-lg"}))
    code = forms.CharField(label='Printer Code', max_length=10,widget=forms.TextInput(attrs={'class': "input-lg"}))    
    description = forms.CharField(label='Printer Description')
    
class LabItemTypeForm(forms.ModelForm):
    name = forms.CharField(label='Printer Name', max_length=200,widget=forms.TextInput(attrs={'class': "input-lg"}))
    code = forms.CharField(label='Printer Code', max_length=10,widget=forms.TextInput(attrs={'class': "input-lg"}))    
    description = forms.CharField(label='Printer Description')

class CollectionTypeForm(forms.ModelForm):
    name = forms.CharField(label='Printer Name', max_length=200,widget=forms.TextInput(attrs={'class': "input-lg"}))
    code = forms.CharField(label='Printer Code', max_length=10,widget=forms.TextInput(attrs={'class': "input-lg"}))    
    description = forms.CharField(label='Printer Description')
    
class OrthoModoJobForm(forms.ModelForm):
    orthotrac_analysis_notes = forms.CharField(label='Orthotrac ANalysis Notes')
    
class LabItemForm(forms.ModelForm):
    is_blocked = forms.CharField(label='Printer Name', max_length=200,widget=forms.TextInput(attrs={'class': "input-lg"}))

    

templates/orthomodoweb/labitem/labitem_add_form.html
{% extends 'orthomodoweb/base.html' %}
{% block content %}
<script>
		$(document).ready(function() {
			$('#id_made_date').datepicker({ dateFormat: 'yy-mm-dd' });		
		});
	</script>	
		
	<div class="form_header">ADD New Lab Item (Retainer Or Gumshield) to an Ortho Job</div>
	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
	<div class = "formcontainer_f">	
		<form action="" method="post">
			{% csrf_token %}
			
			<i class="fa fa-magnet" aria-hidden="true"></i> <label for="id_lab_item_type">LAB ITEM TYPE:</label>				 
				<select name="lab_item_type" id = "id_lab_item_type">				
					{% for lit in lab_item_type_list %}
						{% ifequal labitem.lab_item_type.id lit.id %}
							<option value="{{ lit.id }}" selected="selected">{{ lit.name }} {{ lit.code }}</option>
						{% else %}
							<option value="{{ lit.id }}">{{ lit.name }} {{ lit.code }}</option>	
						{% endifequal %}
					{% endfor %}
				</select>	
			<br /><br />	
			<i class="fa fa-lemon-o" aria-hidden="true"></i> <label for="id_lab_item_material">LAB ITEM MATERIAL:</label>				 
				<select name="lab_item_material" id = "id_lab_item_material">				
					{% for lim in lab_item_material_list %}
						{% ifequal labitem.lab_item_material.id lim.id %}
							<option value="{{ lim.id }}" selected="selected">{{ lim.name }} {{ lim.code }}</option>
						{% else %}
							<option value="{{ lim.id }}">{{ lim.name }} {{ lim.code }}</option>	
						{% endifequal %}
					{% endfor %}
				</select>	
			
			<br /><br />
			<i class="fa fa-adjust" aria-hidden="true"></i> <label for="id_is_blocked">NEEDS TO BE BLOCKED?</label>
			<input type="checkbox" name="is_blocked" id="id_is_blocked" {% if labitem.is_blocked %}checked{% endif %} >
			
			<div class="form_highlight_box_1">
			<i class="fa fa-adjust" aria-hidden="true"></i> <label for="id_is_made">IS MADE?</label>
			<input type="checkbox" name="is_made" id="id_is_made" {% if labitem.is_made %}checked{% endif %} >
			<br /><br />
			<i class="fa fa-calendar" aria-hidden="true"></i> <label for="id_made_date">DATE MADE:</label>
			<input type="text" name="made_date" id="id_made_date" maxlength="100" placeholder = "Date Made" value = '{{ labitem.made_date|date:"Y-m-d" }}'>
			</div>
			
			<br />
			
			<i class="fa fa-sticky-note-o" aria-hidden="true"></i> <label for="id_notes">LAB ITEM NOTES:</label>						
			<br />
			<textarea  rows="5" cols="120" name="notes" id="id_notes" placeholder = "Lab Item Notes">{{ labitem.notes }}</textarea>
						
			
			<br /><br />
			<input class="button"type="submit" value="SAVE" />
			
			<input type=hidden name="orthomodojob_id" value="{{ j_id }}">			
			
		 </form>
		
	</div>	
	 
{% endblock %}

templates/orthomodoweb/labitem/labitem_form.html
{% extends 'orthomodoweb/base.html' %}
{% block content %}
<script>
		$(document).ready(function() {
			$('#id_made_date').datepicker({ dateFormat: 'yy-mm-dd' });		
		});
	</script>	
		
	<div class="form_header">Lab Item (Retainer Or Gumshield) {{ labitem.id }}</div>
	
	
	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
	<div class = "formcontainer_f">	
		<form action="" method="post">
			{% csrf_token %}
			
			<h4><a href="{% url 'orthomodoweb:orthomodojob-update' labitem.orthomodojob.id %}">OMJOB_{{labitem.orthomodojob.id}}</a></h4>
			
			<h3>
				<span style="font-family: 'Lucida Console', Monaco, monospace;">
					{{labitem.lab_item_type.code}}
					<span style="color: #f5f2f2;background-color: #000000;">{{labitem.lab_item_material.code}}</span>
					{{labitem.is_blocked|yesno:"B,U"}}
					<span style="color:#ec3c3c">{{labitem.is_made|yesno:"M,U"}}</span>
					{{labitem.made_date|date:"m-d"}}
				</span>
			</h3>
			
			<i class="fa fa-magnet" aria-hidden="true"></i> <label for="id_lab_item_type">LAB ITEM TYPE:</label>				 
				<select name="lab_item_type" id = "id_lab_item_type">				
					{% for lit in lab_item_type_list %}
						{% ifequal labitem.lab_item_type.id lit.id %}
							<option value="{{ lit.id }}" selected="selected">{{ lit.name }} {{ lit.code }}</option>
						{% else %}
							<option value="{{ lit.id }}">{{ lit.name }} {{ lit.code }}</option>	
						{% endifequal %}
					{% endfor %}
				</select>	
			<br /><br />	
			<i class="fa fa-lemon-o" aria-hidden="true"></i> <label for="id_lab_item_material">LAB ITEM MATERIAL:</label>				 
				<select name="lab_item_material" id = "id_lab_item_material">				
					{% for lim in lab_item_material_list %}
						{% ifequal labitem.lab_item_material.id lim.id %}
							<option value="{{ lim.id }}" selected="selected">{{ lim.name }} {{ lim.code }}</option>
						{% else %}
							<option value="{{ lim.id }}">{{ lim.name }} {{ lim.code }}</option>	
						{% endifequal %}
					{% endfor %}
				</select>	
			
			<br /><br />
			<i class="fa fa-adjust" aria-hidden="true"></i> <label for="id_is_blocked">NEEDS TO BE BLOCKED?</label>
			<input type="checkbox" name="is_blocked" id="id_is_blocked" {% if labitem.is_blocked %}checked{% endif %} >
			
			<div class="form_highlight_box_1">
			<i class="fa fa-adjust" aria-hidden="true"></i> <label for="id_is_made">IS MADE?</label>
			<input type="checkbox" name="is_made" id="id_is_made" {% if labitem.is_made %}checked{% endif %} >
			<br /><br />
			<i class="fa fa-calendar" aria-hidden="true"></i> <label for="id_made_date">DATE MADE:</label>
			<input type="text" name="made_date" id="id_made_date" maxlength="100" placeholder = "Date Made" value = '{{ labitem.made_date|date:"Y-m-d" }}'>
			</div>
			
			<br />
			
			<i class="fa fa-sticky-note-o" aria-hidden="true"></i> <label for="id_notes">LAB ITEM NOTES:</label>						
			<br />
			<textarea  rows="5" cols="120" name="notes" id="id_notes" placeholder = "Lab Item Notes">{{ labitem.notes }}</textarea>
						
			<input type=hidden name="orthomodojob_id" value="{{ j_id }}">
			<br /><br />
			<input class="button"type="submit" value="SAVE" />
		 </form>
		
	</div>	
	 
{% endblock %}

templates/orthomodoweb/labitem/labitem_list.html
{% extends 'orthomodoweb/base.html' %}
{% block content %}
	<div class="standard_page_container">
		<div class="standard_page_container_header">lab Items: {{ total_all_labitems }}</div>
		
		{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
		
		<form id="searchform" action="" method="get" accept-charset="utf-8">
			<input class="searchfield" id="searchbox" name="q" type="text" placeholder="Search" value="{% if search_applied %}{{ search_applied }}{% endif %}"/>
			<button class="searchbutton" type="submit">
				<i class="search-button-text">Search</i>
			</button>
			<label for="id_hide_made_items">HIDE MADE ITEMS</label><input type="checkbox" name="hide_made_items" id="id_hide_made_items" {% if hide_made_items_filter %} checked {% endif %}>
			&nbsp;<label for="id_blocked_only_items">BLOCKED ONLY</label><input type="checkbox" name="blocked_only_items" id="id_blocked_only_items" {% if blocked_only_items_filter %} checked {% endif %}>
		</form>
		{% if search_applied %}<div class="search_applied"> SEARCH APPLIED <span class='search_text'>{{ search_applied }}</span> (<a href="{% url 'orthomodoweb:labitem-list' %}">CLEAR</a>)</div>{% endif %}	  
		
		{% if object_list  %}			
			<table style="background-color:#ffffff">
				<tr>
					<th colspan= "4" class="header_group_2">JOB</th>
					
					<th colspan = "8" class="thickborderleft header_group_4">LAB ITEM</th>
					
				</tr>
				<tr>
					<th>JOB ID</th>
					<th>TYPE</th>
					<th>PATIENT NAME</th>
					<th>IS COLLECTED?</th>
					<th class="thickborderleft">ID</th>
					<th>SHORTCODE</th>
					<th>TYPE</th>
					<th>MATERIAL</th>
					<th>BLOCKED</th>
					<th>MADE?</th>
					<th>DATE MADE</th>
					<th>NOTES</th>
				</tr>
				{% for lab_item in object_list  %}
					<tr>
						<td><a href="{% url 'orthomodoweb:orthomodojob-update' lab_item.orthomodojob.id %}">OMJOB_{{ lab_item.orthomodojob.id }}</a></td>
						<td>{{ lab_item.orthomodojob.model_type.name }}</td>
						<td><a href="{% url 'orthomodoweb:patient-update' lab_item.orthomodojob.patient.id %}">{{ lab_item.orthomodojob.patient.code }}: {{ lab_item.orthomodojob.patient.name }}</a></td>
						<td>{{ lab_item.orthomodojob.is_collected|yesno:"Yes,No" }}</td>
						<td class="thickborderleft"><a href="{% url 'orthomodoweb:labitem-update' orthomodojob_id=lab_item.orthomodojob.id pk=lab_item.id%}">LAB ITEM {{ lab_item.id }}</a></td>
						<td>
							<span style="font-family: 'Lucida Console', Monaco, monospace;">
							{{lab_item.lab_item_type.code}}
							<span style="color: #f5f2f2;background-color: #000000;">{{lab_item.lab_item_material.code}}</span>
							{{lab_item.is_blocked|yesno:"B,U"}}
							<span style="color:#ec3c3c">{{lab_item.is_made|yesno:"M,U"}}</span>
							{{lab_item.made_date|date:"m-d"}}
							</span>
						</td>
						<td>{{ lab_item.lab_item_type.name }}</td>
						<td>{{ lab_item.lab_item_material.name }}</td>
						<td>{{ lab_item.is_blocked|yesno:"Yes,No"  }}</td>
						<td>{{ lab_item.is_made|yesno:"Yes,No"  }}</td>
						<td>{{ lab_item.made_date|date:"Y-m-d" }}</td>
						<td>{{ lab_item.notes }}</td>
					</tr>	
				{% endfor %}	

				</table>
				
			
		{% else %}
			<p>No Lab items found.</p>
		{% endif %}
		
	</div>

{% endblock %}