urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView

from . import views

app_name='orthomodoweb'

urlpatterns = [
    #home page
    url(r'^$',views.HomeView.as_view(),name='home'),
    
    #About/Help page
    url(r'^guide/$',views.UserGuide.as_view(),name='userguide'),    
       
    #export
    url(r'^export_as_csv/$',views.export_as_csv,name='export_as_csv'),
    
    #orthomodojob
    url(r'^orthomodojob/open/$', views.OrthoModoJobViewOpen.as_view(), name='orthomodojob-open-list'),
    url(r'^orthomodojob/all/$', views.OrthoModoJobViewAll.as_view(), name='orthomodojob-all-list'),
    url(r'^orthomodojob/add/$', views.OrthoModoJobCreate.as_view(), name='orthomodojob-add'),
    url(r'^orthomodojob/(?P<pk>[0-9]+)/$', views.OrthoModoJobUpdate.as_view(), name='orthomodojob-update'),
    url(r'^orthomodojob/(?P<pk>[0-9]+)/delete$', views.OrthoModoJobDelete.as_view(), name='orthomodojob-delete'),
       
    #login/logout/signup
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'orthomodoweb:home'}, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^admin/', admin.site.urls),
    
    #printers
    url(r'^printer/$', views.PrinterView.as_view(), name='printer-list'),
    url(r'^printer/add/$', views.PrinterCreate.as_view(), name='printer-add'),
    url(r'^printer/(?P<pk>[0-9]+)/$', views.PrinterUpdate.as_view(), name='printer-update'),
    url(r'^printer/(?P<pk>[0-9]+)/delete$', views.PrinterDelete.as_view(), name='printer-delete'),
    
    #patients
    url(r'^patient/$', views.PatientView.as_view(), name='patient-list'),
    url(r'^patient/add/$', views.PatientCreate.as_view(), name='patient-add'),
    url(r'^patient/(?P<pk>[0-9]+)/$', views.PatientUpdate.as_view(), name='patient-update'),
    url(r'^patient/(?P<pk>[0-9]+)/delete$', views.PatientDelete.as_view(), name='patient-delete'),
    url(r'^patient/(?P<patient_id>[0-9]+)/addjob$', views.OrthoModoPatientJobCreate.as_view(), name='patient-add-job'),
    
    #clinicians
    url(r'^clinician/$', views.ClinicianView.as_view(), name='clinician-list'),
    url(r'^clinician/add/$', views.ClinicianCreate.as_view(), name='clinician-add'),
    url(r'^clinician/(?P<pk>[0-9]+)/$', views.ClinicianUpdate.as_view(), name='clinician-update'),
    url(r'^clinician/(?P<pk>[0-9]+)/delete$', views.ClinicianDelete.as_view(), name='clinician-delete'),
    
    #labitemtypes
    url(r'^labitemtype/$', views.LabItemTypeView.as_view(), name='labitemtype-list'),
    url(r'^labitemtype/add/$', views.LabItemTypeCreate.as_view(), name='labitemtype-add'),
    url(r'^labitemtype/(?P<pk>[0-9]+)/$', views.LabItemTypeUpdate.as_view(), name='labitemtype-update'),
    url(r'^labitemtype/(?P<pk>[0-9]+)/delete$', views.LabItemTypeDelete.as_view(), name='labitemtype-delete'),
    
     #collectiontype
    url(r'^collectiontype/$', views.CollectionTypeView.as_view(), name='collectiontype-list'),
    url(r'^collectiontype/add/$', views.CollectionTypeCreate.as_view(), name='collectiontype-add'),
    url(r'^collectiontype/(?P<pk>[0-9]+)/$', views.CollectionTypeUpdate.as_view(), name='collectiontype-update'),
    url(r'^collectiontype/(?P<pk>[0-9]+)/delete$', views.CollectionTypeDelete.as_view(), name='collectiontype-delete'),
    
    #labitems
     url(r'^(?P<orthomodojob_id>[0-9]+)/labitem/add/$', views.LabItemCreate.as_view(), name='labitem-create'),
     url(r'^(?P<orthomodojob_id>[0-9]+)/labitem/(?P<pk>[0-9]+)/$', views.LabItemUpdate.as_view(), name='labitem-update'),
     url(r'^orthomodojob/labitem/$', views.LabItemView.as_view(), name='labitem-list'),
     
     #redirect everything unknown to the home pahe
     #url(r'^.*$', RedirectView.as_view(pattern_name='home', permanent=False), name='index')
]

forms.py
from django import forms
from .models import Printer
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class PrinterForm(forms.ModelForm):
    name = forms.CharField(label='Printer Name', max_length=200,widget=forms.TextInput(attrs={'class': "input-lg"}))
    code = forms.CharField(label='Printer Code', max_length=10,widget=forms.TextInput(attrs={'class': "input-lg"}))    
    description = forms.CharField(label='Printer Description')
    
class PatientForm(forms.ModelForm):
    name = forms.CharField(label='Printer Name', max_length=200,widget=forms.TextInput(attrs={'class': "input-lg"}))
    code = forms.CharField(label='Printer Code', max_length=10,widget=forms.TextInput(attrs={'class': "input-lg"}))    
    description = forms.CharField(label='Printer Description')
    
class ClinicianForm(forms.ModelForm):
    name = forms.CharField(label='Printer Name', max_length=200,widget=forms.TextInput(attrs={'class': "input-lg"}))
    code = forms.CharField(label='Printer Code', max_length=10,widget=forms.TextInput(attrs={'class': "input-lg"}))    
    description = forms.CharField(label='Printer Description')
    
class LabItemTypeForm(forms.ModelForm):
    name = forms.CharField(label='Printer Name', max_length=200,widget=forms.TextInput(attrs={'class': "input-lg"}))
    code = forms.CharField(label='Printer Code', max_length=10,widget=forms.TextInput(attrs={'class': "input-lg"}))    
    description = forms.CharField(label='Printer Description')

class CollectionTypeForm(forms.ModelForm):
    name = forms.CharField(label='Printer Name', max_length=200,widget=forms.TextInput(attrs={'class': "input-lg"}))
    code = forms.CharField(label='Printer Code', max_length=10,widget=forms.TextInput(attrs={'class': "input-lg"}))    
    description = forms.CharField(label='Printer Description')
    
class OrthoModoJobForm(forms.ModelForm):
    orthotrac_analysis_notes = forms.CharField(label='Orthotrac ANalysis Notes')
    
class LabItemForm(forms.ModelForm):
    is_blocked = forms.CharField(label='Printer Name', max_length=200,widget=forms.TextInput(attrs={'class': "input-lg"}))

    

views.py
from django.http import Http404
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.base import TemplateView
from django.views.generic import DetailView, FormView
from django.utils import timezone
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login, authenticate
#from django.contrib.auth.forms import UserCreationForm
import math
import sys
from datetime import datetime, timedelta, time
from django.contrib.auth.models import User
from django import forms

from django.db import connections
from django.db.models import Count, Min, Sum, Avg, F, Q
from django.http import JsonResponse

from django.core.mail import send_mail

from functools import reduce
import operator

from django.conf import settings

import csv


from .models import Printer, Patient, Clinician, ModelType, LabItemType, CollectionType, OrthoModoJob, LabItem, LabItemMaterial, CreatedModelUse

from orthomodoweb.forms import UserCreationForm, PrinterForm, PatientForm, ClinicianForm,LabItemTypeForm, CollectionTypeForm, OrthoModoJobForm, LabItemForm

from django.core.exceptions import ImproperlyConfigured

import logging

logger = logging.getLogger("django")


#***************HOME PAGE***********
class HomeView(TemplateView):
    template_name = 'orthomodoweb/home.html'
    def get_context_data(self, **kwargs):
       
        context=super(HomeView,self).get_context_data(**kwargs)
        today = datetime.now().date()
        tomorrow = today + timedelta(1)
        activity_date_start = datetime.combine(today, time())
        activity_date_end = datetime.combine(tomorrow, time())         
        activity_date = today
        print(self.request.GET, file=sys.stderr) 
        
        if self.request.GET.get('activity_date'):
            activity_date_str = self.request.GET.get('activity_date')
            activity_date = datetime.strptime(activity_date_str, '%Y-%m-%d')
        if activity_date:
            activity_date_start = datetime.combine(activity_date, time())
            activity_date_end = datetime.combine(activity_date+timedelta(1), time())
        print('activity_date: ', file=sys.stderr)     
        print(activity_date, file=sys.stderr)     
        #get jobs that have the selected date as the scan date (today)
        context['activity_date'] =  activity_date
        context['selected_day_jobs_scandate'] =  OrthoModoJob.objects.filter(scan_date__lte=activity_date_end, scan_date__gte=activity_date_start) 
        context['selected_day_jobs_printdate'] =  OrthoModoJob.objects.filter(print_date__lte=activity_date_end, print_date__gte=activity_date_start) 
        context['selected_day_jobs_plannedcollectiondate'] =  OrthoModoJob.objects.filter(planned_collection_date__lte=activity_date_end, planned_collection_date__gte=activity_date_start) 
        context['selected_day_jobs_dateupdated'] =  OrthoModoJob.objects.filter(date_updated__lte=activity_date_end, date_updated__gte=activity_date_start) 
        
        logger.info('Getting Homepage data get_context_data()')
        return context
		

#*********USER GUIDE**********************
class UserGuide(TemplateView):
	template_name = "orthomodoweb/guide.html"
    
#**************SIGNUP*****************
class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=40, required=True)
    last_name = forms.CharField(max_length=40, required=True)
    email = forms.EmailField(max_length=254, help_text='Account info WILL be sent for reference, so use your own (valid) email address!!')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )
        
def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        logger.info('Signup form submitted')
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            email = form.cleaned_data.get('email')
            user = authenticate(username=username, password=raw_password)
            #Try send an email upon registering user
            emailText = 'Thank you for setting up an account on the OrthoModo System.\n\n Your username is ' + username + '. Your password is ' + raw_password + '. \n\nPlease do not share these details.\n\nDo not reply to or forward this email. For support, use donakello@gmail.com'
            send_mail('OrthoModo System Account Created', emailText, 'orthomodo@donalkelly.com', [email])
            login(request, user)
            return redirect('orthomodoweb:home')
    else:
        logger.info('Signup form loaded')
        form = SignUpForm()  
    return render(request, 'registration/signup.html', {'form': form})

        
        
def export_as_csv(request):
    # Create the HttpResponse object with the appropriate CSV header.
    logger.info('CSV export link clicked')
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="orthomodo_export.csv"'

    writer = csv.writer(response,delimiter=',', quoting=csv.QUOTE_ALL, quotechar='"')
    writer.writerow(["patient.name", "patient.code", "clinician.name", "scan_date", "scan_date_entered_by", "scan_date_entered_when", "orthotrac_analysis_done", "orthotrac_analysis_notes", "printer", "is_stl_file_prepared", "stl_marked_as_prepared_by", "stl_marked_as_prepared_when", "is_printed", "print_date", "is_printed_marked_by", "is_printed_marked_when", "collection_type", "planned_collection_date", "planned_collection_time", "collection_notes", "is_collected", "is_collected_marked_by", "is_collected_marked_when", "flagged", "flag_status_set_by", "flag_status_set_when", "flag_status_note", "last_updated_by", "date_updated", "created_by", "date_created","lab Item ID","lab_item_type","lab_item_material","is_blocked","is_made","made_date","is_made_marked_by","is_made_marked_when","notes","last_updated_by","date_updated","created_by","date_created"])
    
    for omj in OrthoModoJob.objects.all():
        #need to check if there are lab items: if so we need aline for each lab item
        if omj.labitem_set.count() == 0:
            writer.writerow([omj.patient.name.replace('\r\n', '\\n'), omj.patient.code, omj.clinician.name.replace('\r\n', '\\n'), omj.scan_date, omj.scan_date_entered_by, omj.scan_date_entered_when, omj.orthotrac_analysis_done, omj.orthotrac_analysis_notes, omj.printer, omj.is_stl_file_prepared, omj.stl_marked_as_prepared_by, omj.stl_marked_as_prepared_when, omj.is_printed, omj.print_date, omj.is_printed_marked_by, omj.is_printed_marked_when, omj.collection_type, omj.planned_collection_date, omj.planned_collection_time, omj.collection_notes.replace('\r\n', '\\n'), omj.is_collected, omj.is_collected_marked_by, omj.is_collected_marked_when, omj.flagged, omj.flag_status_set_by, omj.flag_status_set_when, omj.flag_status_note.replace('\r\n', '\\n'), omj.last_updated_by, omj.date_updated, omj.created_by, omj.date_created,None,None,None,None,None,None,None,None,None,None,None,None,None,])
        else:#write a line for each lab item. Job item details repeat
            for omjli in omj.labitem_set.all():
                    writer.writerow([omj.patient.name.replace('\r\n', '\\n'), omj.patient.code, omj.clinician.name.replace('\r\n', '\\n'), omj.scan_date, omj.scan_date_entered_by, omj.scan_date_entered_when, omj.orthotrac_analysis_done, omj.orthotrac_analysis_notes, omj.printer, omj.is_stl_file_prepared, omj.stl_marked_as_prepared_by, omj.stl_marked_as_prepared_when, omj.is_printed, omj.print_date, omj.is_printed_marked_by, omj.is_printed_marked_when, omj.collection_type, omj.planned_collection_date, omj.planned_collection_time, omj.collection_notes.replace('\r\n', '\\n'), omj.is_collected, omj.is_collected_marked_by, omj.is_collected_marked_when, omj.flagged, omj.flag_status_set_by, omj.flag_status_set_when, omj.flag_status_note.replace('\r\n', '\\n'), omj.last_updated_by, omj.date_updated, omj.created_by, omj.date_created,omjli.id,omjli.lab_item_type,omjli.lab_item_material,omjli.is_blocked,omjli.is_made,omjli.made_date,omjli.is_made_marked_by,omjli.is_made_marked_when,omjli.notes.replace('\r\n', '\\n'),omjli.last_updated_by,omjli.date_updated,omjli.created_by,omjli.date_created])
    logger.info('CSV export ready to be returned')
    return response

#**************OrthoModoJob*****************
class OrthoModoJobViewOpen(LoginRequiredMixin,generic.ListView):
    login_url = 'orthomodoweb:login'
    redirect_field_name = 'orthomodoweb:home'
    model = OrthoModoJob
    template_name = 'orthomodoweb/orthomodojob/orthomodojob_open_list.html'   
     
     
    def get_context_data(self, **kwargs):
        logger.info('OrthoModoJobViewOpen get_context_data()')
        context=super(OrthoModoJobViewOpen,self).get_context_data(**kwargs)
        context['total_open_jobs'] =  OrthoModoJob.objects.filter(Q(flagged=True) | Q(is_collected=False)).count() 
        query = self.request.GET.get('q')
        is_flagged_filter = self.request.GET.get('is_flagged')
        is_analysed_filter = self.request.GET.get('is_analysed')
        is_printed_filter = self.request.GET.get('is_printed')
        if query:
            query_list = query.split()
            print('Searching for ', file=sys.stderr)
            print('-'.join(query_list), file=sys.stderr)
            context['search_applied'] = '-'.join(query_list)
        if is_flagged_filter=='on':
            context['is_flagged_filter'] = '1'
        if is_analysed_filter=='on':
            context['is_analysed_filter'] = '1'
        if is_printed_filter=='on':
            context['is_printed_filter'] = '1'
        return context

templates/orthomodoweb/patient/patient_confirm_delete.html
{% extends 'orthomodoweb/base.html' %}
{% block content %}
	<h1>Patient: DELETE</h1>
	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

	<form action="" method="post">{% csrf_token %}
		<p>Are you sure you want to delete "{{ object }}"?</p>
		<input type="submit" value="Confirm" />
	</form>
{% endblock %}

templates/orthomodoweb/patient/patient_form.html
{% extends 'orthomodoweb/base.html' %}
{% block content %}

	<script>
		$(document).ready(function() {
			$('#id_dob').datepicker({ dateFormat: 'yy-mm-dd' });
		});
	</script>

	 
	
	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
	<div class="formcontainer">
		<div class="form_header">Patient Details: {{ patient.name }}</div>
		<form action="{% url 'orthomodoweb:patient-update' pk=patient.id %}" method="post">
			{% csrf_token %}
			<div class="column form_left_container">
			
				<i class="fa fa-address-card-o" aria-hidden="true"></i>  <label for="id_code">CODE: </label>
				<input type="text" name="code" id="id_code" maxlength="200" placeholder = "Code (unique)" value = '{{ patient.code }}'>
				<br /><br />
				<i class="fa fa-user-circle" aria-hidden="true"></i> <label for="id_name">NAME:</label>
				<input type="text" name="name" id="id_name" maxlength="200" placeholder = "Name" value = "{{ patient.name }}">
				<br /><br />
				<i class="fa fa-share-square" aria-hidden="true"></i> <label for="id_reference_no">REFERENCE NUMBER:</label>				 
				<input type="text" name="reference_no" id="id_reference_no" maxlength="200" placeholder = "Reference No" value = '{{ patient.reference_no }}'>
				<br /><br />
				<i class="fa fa-envelope-o" aria-hidden="true"></i> <label for="id_email">EMAIL:</label>
				<input type="text" name="email" id="id_email" maxlength="200" placeholder = "email" value = '{{ patient.email }}'>
				<br /><br />
				<i class="fa fa-phone" aria-hidden="true"></i> <label for="id_phone_no_1">PHONE NO. 1:</label>
				<input type="text" name="phone_no_1" id="id_phone_no_1" maxlength="200" placeholder = "phone no 1" value = '{{ patient.phone_no_1 }}'>
				<br /><br />
				<i class="fa fa-mobile" aria-hidden="true"></i> <label for="id_phone_no_2">PHONE NO. 2:</label>
				<input type="text" name="phone_no_2" id="id_phone_no_2" maxlength="200" placeholder = "phone no 2" value = '{{ patient.phone_no_2 }}'>
				<br /><br />
			</div>
			<div class="column form_right_container">
				<i class="fa fa-calendar" aria-hidden="true"></i> <label for="id_dob">DATE OF BIRTH:</label>
				<input type="text" name="dob" id="id_dob" maxlength="200" placeholder = "" value = '{{ patient.dob|date:"Y-m-d" }}'>
				<br /><br />
				<i class="fa fa-map-marker" aria-hidden="true"></i> <label for="id_address">ADDRESS:</label>
				<input type="text" name="address" id="id_address" maxlength="300" placeholder = "address" value = '{{ patient.address }}'>
				<br /><br />
				<i class="fa fa-sticky-note-o" aria-hidden="true"></i> <label for="id_description">DESCRIPTION/NOTES:</label>				
				<br />
				<textarea  rows="8" cols="82" name="description" id="id_description" placeholder = "description/notes">{{ patient.description }}</textarea>		
				<br /><br />
				<input type="submit" value="SAVE" class="button" />
				<br /><br /><br />
				<a class="button" href="{% url 'orthomodoweb:patient-add-job' patient_id=patient.id %}">Add JOB for this Patient</a>	
			</div>
		 </form>
	</div>
	<div class="datatable">
	<div class = "datatable_header">Patient Jobs</div>
	
		<table>
		<tr>
				<th colspan="5" class="header_group_1">Basic Info</th>
				<th colspan="2" class="thickborderleft header_group_2">Orthotrac Analysis</th>
				<th colspan="4" class="thickborderleft header_group_3">3D Printed Model</th>
				<th colspan="2" class="thickborderleft header_group_3">Plaster Model</th>
				<th colspan="1" class="thickborderleft header_group_3">Use For</th>
				<th colspan="2" class="thickborderleft header_group_4">Lab Items</th>
				<th colspan="5" class="thickborderleft header_group_5">Collection</th>
				<th colspan="2" class="thickborderleft header_group_6">Flag Status</th>
				<th colspan="2" class="thickborderleft header_group_1">Last Updated</th>
			</tr>
			<tr>
				<th>ID</th>
				<th>Model type</th>
				<th>Scan&nbsp;Date</th>
				<th>Patient</th>
				<th>Clinician</th>				
				<th class="thickborderleft">Done?</th>
				<th>Notes</th>
				<th class="thickborderleft">Printer</th>
				<th>STL file?</th>
				<th>Printed?</th>
				<th>Print Date</th>
				<th class="thickborderleft">Poured?</th>
				<th>Pour Date</th>
				<th class="thickborderleft">&nbsp;&nbsp;&nbsp;&nbsp;Use&nbsp;&nbsp;&nbsp;&nbsp;</th>
				<th class="thickborderleft">Qty</th>
				<th>&nbsp;Item&nbsp;Details&nbsp;&nbsp;</th>
				<th class="thickborderleft">Type</th>
				<th>Planned Date</th>
				<th>Time</th>
				<th>Notes</th>
				<th>Collected?</th>
				<th class="thickborderleft">Status</th>
				<th >Notes</th>
				<th >By</th>
				<th >When</th>
			</tr>
		{% if patient.orthomodojob_set %}
			{% for orthomodojob in patient.orthomodojob_set.all|dictsortreversed:"id"  %}
				<tr>
			
				<td><a href="{% url 'orthomodoweb:orthomodojob-update' orthomodojob.id %}">OMJOB_{{ orthomodojob.id }}</a></td>
				<td>{{ orthomodojob.model_type }}</td>
				<td>{{ orthomodojob.scan_date|date:"y-m-d" }}</td>
				<td><a href="{% url 'orthomodoweb:patient-update' orthomodojob.patient.id %}">{{orthomodojob.patient.code}}: {{ orthomodojob.patient.name }}</a></td>
				<td>{% if orthomodojob.clinician %}<a href="{% url 'orthomodoweb:clinician-update' orthomodojob.clinician.id %}">{{ orthomodojob.clinician.name }}</a>{% endif %}</td> 			
				<td class="thickborderleft">{{ orthomodojob.orthotrac_analysis_done|yesno:"Yes,No" }}</td>
				<td class="compact_table_cell_normal_font">{{ orthomodojob.orthotrac_analysis_notes|truncatechars:30 }}</td>
				<td class="thickborderleft">{% if orthomodojob.printer %}<a href="{% url 'orthomodoweb:printer-update' orthomodojob.printer.id %}">{{ orthomodojob.printer.name }}</a>{% endif %}</td>
				<td>{{ orthomodojob.is_stl_file_prepared|yesno:"Yes,No" }}</td>
				<td>{{ orthomodojob.is_printed|yesno:"Yes,No" }}</td>
				<td>{{ orthomodojob.print_date|date:"y-m-d" }}</td>
				<td class="thickborderleft">{{ orthomodojob.is_poured|yesno:"Yes,No" }}</td>
				<td>{{ orthomodojob.poured_date|date:"y-m-d" }}</td>
				<td class="thickborderleft">{{ orthomodojob.created_model_use.code }}</td>
				<td class="thickborderleft">{{ orthomodojob.labitem_set.count }}</td>
				<td> {% for lab_item in orthomodojob.labitem_set.all  %}
						
							<span class="compact_table_cell">
							{{lab_item.lab_item_type.code}}
							<span style="color: #f5f2f2;background-color: #000000;">{{lab_item.lab_item_material.code}}</span>
							{{lab_item.is_blocked|yesno:"B,U"}}
							<span style="color:#ec3c3c">{{lab_item.is_made|yesno:"M,U"}}
							</span>{{lab_item.made_date|date:"m-d"}}<br />
							</span>
							
					{% endfor %}	</td>
				<td class="thickborderleft">{% if orthomodojob.collection_type %}<a href="{% url 'orthomodoweb:collectiontype-update' orthomodojob.collection_type.id %}">{{ orthomodojob.collection_type.name }}</a>{% endif %}</td>
				<td>{{orthomodojob.planned_collection_date|date:"y-m-d"}}</td>
				<td>{{orthomodojob.planned_collection_time}}</td>
				<td class="compact_table_cell_normal_font">{{orthomodojob.collection_notes|truncatechars:30}}</td>			
				<td>{{orthomodojob.is_collected|yesno:"Yes,No"}}</td>
				<td class="thickborderleft status{% if orthomodojob.flagged %}_flagged{% endif %}">{{ orthomodojob.flagged|yesno:"FLAGGED,normal" }}</td>
				<td class="compact_table_cell_normal_font status{% if orthomodojob.flagged %}_flagged{% endif %}">{{ orthomodojob.flag_status_note|truncatechars:30 }}</td>
				<td class="compact_table_cell_normal_font">{{ orthomodojob.last_updated_by }}</td>
				<td class="compact_table_cell_normal_font">{{ orthomodojob.date_updated|date:'y-m-d (H:i)' }}</td>
				</tr>
			{% endfor %}
			</table>	
		
		{% else %}
			</table>
			<p class="emptylist">No OrthoModoJobs found for this patient.</p>
		{% endif %}
	</div>
	<div class="bottom_action_links">		 
			<!-- <a class="button" href="{% url 'orthomodoweb:patient-add-job' patient_id=patient.id %}">Add JOB for this Patient</a>		 -->
		
			<!-- <a class="button" href="{% url 'orthomodoweb:patient-add' %}">Add NEW Patient</a> -->
		
		 
			<!-- <a class="button_red" href="{% url 'orthomodoweb:patient-delete' patient.id%}">Delete this Patient</a> -->
		
	</div>
	

{% endblock %}

templates/orthomodoweb/patient/patientconfirm_delete.html
{% extends 'orthomodoweb/base.html' %}
{% block content %}
	<h1>Patient: DELETE</h1>
	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

	<form action="" method="post">{% csrf_token %}
		<p>Are you sure you want to delete "{{ object }}"?</p>
		<input type="submit" value="Confirm" />
	</form>
{% endblock %}