urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView

from . import views

app_name='orthomodoweb'

urlpatterns = [
    #home page
    url(r'^$',views.HomeView.as_view(),name='home'),
    
    #About/Help page
    url(r'^guide/$',views.UserGuide.as_view(),name='userguide'),    
       
    #export
    url(r'^export_as_csv/$',views.export_as_csv,name='export_as_csv'),
    
    #orthomodojob
    url(r'^orthomodojob/open/$', views.OrthoModoJobViewOpen.as_view(), name='orthomodojob-open-list'),
    url(r'^orthomodojob/all/$', views.OrthoModoJobViewAll.as_view(), name='orthomodojob-all-list'),
    url(r'^orthomodojob/add/$', views.OrthoModoJobCreate.as_view(), name='orthomodojob-add'),
    url(r'^orthomodojob/(?P<pk>[0-9]+)/$', views.OrthoModoJobUpdate.as_view(), name='orthomodojob-update'),
    url(r'^orthomodojob/(?P<pk>[0-9]+)/delete$', views.OrthoModoJobDelete.as_view(), name='orthomodojob-delete'),
       
    #login/logout/signup
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'orthomodoweb:home'}, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^admin/', admin.site.urls),
    
    #printers
    url(r'^printer/$', views.PrinterView.as_view(), name='printer-list'),
    url(r'^printer/add/$', views.PrinterCreate.as_view(), name='printer-add'),
    url(r'^printer/(?P<pk>[0-9]+)/$', views.PrinterUpdate.as_view(), name='printer-update'),
    url(r'^printer/(?P<pk>[0-9]+)/delete$', views.PrinterDelete.as_view(), name='printer-delete'),
    
    #patients
    url(r'^patient/$', views.PatientView.as_view(), name='patient-list'),
    url(r'^patient/add/$', views.PatientCreate.as_view(), name='patient-add'),
    url(r'^patient/(?P<pk>[0-9]+)/$', views.PatientUpdate.as_view(), name='patient-update'),
    url(r'^patient/(?P<pk>[0-9]+)/delete$', views.PatientDelete.as_view(), name='patient-delete'),
    url(r'^patient/(?P<patient_id>[0-9]+)/addjob$', views.OrthoModoPatientJobCreate.as_view(), name='patient-add-job'),
    
    #clinicians
    url(r'^clinician/$', views.ClinicianView.as_view(), name='clinician-list'),
    url(r'^clinician/add/$', views.ClinicianCreate.as_view(), name='clinician-add'),
    url(r'^clinician/(?P<pk>[0-9]+)/$', views.ClinicianUpdate.as_view(), name='clinician-update'),
    url(r'^clinician/(?P<pk>[0-9]+)/delete$', views.ClinicianDelete.as_view(), name='clinician-delete'),
    
    #labitemtypes
    url(r'^labitemtype/$', views.LabItemTypeView.as_view(), name='labitemtype-list'),
    url(r'^labitemtype/add/$', views.LabItemTypeCreate.as_view(), name='labitemtype-add'),
    url(r'^labitemtype/(?P<pk>[0-9]+)/$', views.LabItemTypeUpdate.as_view(), name='labitemtype-update'),
    url(r'^labitemtype/(?P<pk>[0-9]+)/delete$', views.LabItemTypeDelete.as_view(), name='labitemtype-delete'),
    
     #collectiontype
    url(r'^collectiontype/$', views.CollectionTypeView.as_view(), name='collectiontype-list'),
    url(r'^collectiontype/add/$', views.CollectionTypeCreate.as_view(), name='collectiontype-add'),
    url(r'^collectiontype/(?P<pk>[0-9]+)/$', views.CollectionTypeUpdate.as_view(), name='collectiontype-update'),
    url(r'^collectiontype/(?P<pk>[0-9]+)/delete$', views.CollectionTypeDelete.as_view(), name='collectiontype-delete'),
    
    #labitems
     url(r'^(?P<orthomodojob_id>[0-9]+)/labitem/add/$', views.LabItemCreate.as_view(), name='labitem-create'),
     url(r'^(?P<orthomodojob_id>[0-9]+)/labitem/(?P<pk>[0-9]+)/$', views.LabItemUpdate.as_view(), name='labitem-update'),
     url(r'^orthomodojob/labitem/$', views.LabItemView.as_view(), name='labitem-list'),
     
     #redirect everything unknown to the home pahe
     #url(r'^.*$', RedirectView.as_view(pattern_name='home', permanent=False), name='index')
]

models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

class Printer(models.Model):
    name = models.CharField(max_length=200)
    code = models.CharField(max_length=10)
    description = models.TextField(blank=True)
    date_updated = models.DateTimeField('Date updated',auto_now=True)
    date_created = models.DateTimeField('Date Created',auto_now_add=True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
       return reverse('orthomodoweb:printer-update', kwargs={'pk': self.pk})

class Patient(models.Model):
    name = models.CharField(max_length=200)
    code = models.CharField(max_length=20,unique=True)
    reference_no = models.CharField(max_length=50,blank=True)
    description = models.TextField(blank=True)
    email = models.EmailField(blank=True)
    phone_no_1 = models.CharField(blank=True,max_length=50)
    phone_no_2 = models.CharField(blank=True,max_length=50)
    address = models.CharField(blank=True,max_length=300)
    dob = models.DateField(blank=True, null=True)
    date_updated = models.DateTimeField('Date updated',auto_now=True)
    date_created = models.DateTimeField('Date Created',auto_now_add=True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
       return reverse('orthomodoweb:patient-update', kwargs={'pk': self.pk})
       
class Clinician(models.Model):
    name = models.CharField(max_length=200)
    code = models.CharField(max_length=20,unique=True)
    description = models.TextField(blank=True)
    date_updated = models.DateTimeField('Date updated',auto_now=True)
    date_created = models.DateTimeField('Date Created',auto_now_add=True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
       return reverse('orthomodoweb:clinician-update', kwargs={'pk': self.pk})
       
class LabItemType(models.Model):
    code = models.CharField(max_length=20,unique=True)
    name = models.CharField(max_length=200)    
    description = models.TextField(blank=True)
    date_updated = models.DateTimeField('Date updated',auto_now=True)
    date_created = models.DateTimeField('Date Created',auto_now_add=True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
       return reverse('orthomodoweb:labitemtype-update', kwargs={'pk': self.pk})

class LabItemMaterial(models.Model):
    code = models.CharField(max_length=20,unique=True)
    name = models.CharField(max_length=200)    
    description = models.TextField(blank=True)
    date_updated = models.DateTimeField('Date updated',auto_now=True)
    date_created = models.DateTimeField('Date Created',auto_now_add=True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
       return reverse('orthomodoweb:labitemmaterial-update', kwargs={'pk': self.pk})
       
       
class CollectionType(models.Model):    
    code = models.CharField(max_length=20,unique=True)
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    date_updated = models.DateTimeField('Date updated',auto_now=True)
    date_created = models.DateTimeField('Date Created',auto_now_add=True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
       return reverse('orthomodoweb:collectiontype-update', kwargs={'pk': self.pk})

class ModelType(models.Model):     
    name = models.CharField(max_length=30, unique=True)
    def __str__(self):
        return self.name
        
class CreatedModelUse(models.Model):     
    code = models.CharField(max_length=20, unique=True)
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name
 
class OrthoModoJob(models.Model):      
    patient = models.ForeignKey(Patient, on_delete=models.PROTECT)
    clinician = models.ForeignKey(Clinician, on_delete=models.PROTECT)
    model_type = models.ForeignKey(ModelType, on_delete=models.PROTECT)
    scan_date = models.DateField(blank=True, null=True)    
    scan_date_entered_by = models.ForeignKey(settings.AUTH_USER_MODEL,blank=True,null=True,related_name="orthomodojob_scan_date_entered_by")
    scan_date_entered_when = models.DateTimeField(blank=True, null=True)    
    orthotrac_analysis_done = models.BooleanField(default=False)
    orthotrac_analysis_notes = models.TextField(blank=True)    
    printer = models.ForeignKey(Printer, on_delete=models.PROTECT,blank=True,null=True)
    is_stl_file_prepared = models.BooleanField(default=False)
    stl_marked_as_prepared_by = models.ForeignKey(settings.AUTH_USER_MODEL,blank=True,null=True,related_name="orthomodojob_stl_marked_as_prepared_by")
    stl_marked_as_prepared_when = models.DateTimeField(blank=True, null=True)    
    is_printed = models.BooleanField(default=False)
    print_date = models.DateField(blank=True, null=True)   
    is_printed_marked_by = models.ForeignKey(settings.AUTH_USER_MODEL,blank=True,null=True,related_name="orthomodojob_is_printed_marked_by")
    is_printed_marked_when = models.DateTimeField(blank=True, null=True)  
    is_poured =  models.BooleanField(default=False)
    poured_date = models.DateField(blank=True, null=True)   
    is_poured_marked_by = models.ForeignKey(settings.AUTH_USER_MODEL,blank=True,null=True,related_name="orthomodojob_is_poured_marked_by")
    is_poured_marked_when = models.DateTimeField(blank=True, null=True) 
    created_model_use = models.ForeignKey(CreatedModelUse, on_delete=models.PROTECT,blank=True,null=True)    
    collection_type = models.ForeignKey(CollectionType, on_delete=models.PROTECT,blank=True,null=True)
    planned_collection_date = models.DateField(blank=True, null=True)    
    planned_collection_time = models.TimeField(blank=True, null=True)
    collection_notes = models.TextField(blank=True)    
    is_collected = models.BooleanField(default=False)
    is_collected_marked_by = models.ForeignKey(settings.AUTH_USER_MODEL,blank=True,null=True,related_name="orthomodojob_is_collected_marked_by")
    is_collected_marked_when = models.DateTimeField(blank=True, null=True)    
    flagged = models.BooleanField(default=False)
    flag_status_set_by = models.ForeignKey(settings.AUTH_USER_MODEL,blank=True,null=True,related_name="orthomodojob_flag_status_set_by")
    flag_status_set_when = models.DateTimeField(blank=True, null=True)
    flag_status_note = models.TextField(blank=True)
    last_updated_by = models.ForeignKey(settings.AUTH_USER_MODEL,blank=True,null=True,related_name="orthomodojob_last_updated_by")
    date_updated = models.DateTimeField('Date updated',auto_now=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL,blank=True,null=True,related_name="orthomodojob_created_by")
    date_created = models.DateTimeField('Date Created',auto_now_add=True)
    def __str__(self):
        return str(self.id)
    def get_absolute_url(self):
       return reverse('orthomodoweb:orthomodojob-update', kwargs={'pk': self.pk})
   
class LabItem(models.Model):
    orthomodojob = models.ForeignKey(OrthoModoJob, on_delete=models.PROTECT)
    lab_item_type = models.ForeignKey(LabItemType, on_delete=models.PROTECT)
    lab_item_material = models.ForeignKey(LabItemMaterial, on_delete=models.PROTECT)
    is_blocked =  models.BooleanField(default=False)
    is_made =  models.BooleanField(default=False)
    made_date = models.DateTimeField(blank=True, null=True)  
    is_made_marked_by = models.ForeignKey(settings.AUTH_USER_MODEL,blank=True,null=True,related_name="lab_item_is_made_marked_by")
    is_made_marked_when = models.DateTimeField(blank=True, null=True)     
    notes= models.TextField(blank=True)
    last_updated_by = models.ForeignKey(settings.AUTH_USER_MODEL,blank=True,null=True,related_name="lab_item_last_updated_by")
    date_updated = models.DateTimeField('Date updated',auto_now=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL,blank=True,null=True,related_name="lab_item_created_by")
    date_created = models.DateTimeField('Date Created',auto_now_add=True)
    def __str__(self):
        return self.lab_item_type.name
    def get_absolute_url(self):
       return reverse('orthomodoweb:orthomodojob-update', kwargs={'pk': self.orthomodojob.id})

forms.py
from django import forms
from .models import Printer
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class PrinterForm(forms.ModelForm):
    name = forms.CharField(label='Printer Name', max_length=200,widget=forms.TextInput(attrs={'class': "input-lg"}))
    code = forms.CharField(label='Printer Code', max_length=10,widget=forms.TextInput(attrs={'class': "input-lg"}))    
    description = forms.CharField(label='Printer Description')
    
class PatientForm(forms.ModelForm):
    name = forms.CharField(label='Printer Name', max_length=200,widget=forms.TextInput(attrs={'class': "input-lg"}))
    code = forms.CharField(label='Printer Code', max_length=10,widget=forms.TextInput(attrs={'class': "input-lg"}))    
    description = forms.CharField(label='Printer Description')
    
class ClinicianForm(forms.ModelForm):
    name = forms.CharField(label='Printer Name', max_length=200,widget=forms.TextInput(attrs={'class': "input-lg"}))
    code = forms.CharField(label='Printer Code', max_length=10,widget=forms.TextInput(attrs={'class': "input-lg"}))    
    description = forms.CharField(label='Printer Description')
    
class LabItemTypeForm(forms.ModelForm):
    name = forms.CharField(label='Printer Name', max_length=200,widget=forms.TextInput(attrs={'class': "input-lg"}))
    code = forms.CharField(label='Printer Code', max_length=10,widget=forms.TextInput(attrs={'class': "input-lg"}))    
    description = forms.CharField(label='Printer Description')

class CollectionTypeForm(forms.ModelForm):
    name = forms.CharField(label='Printer Name', max_length=200,widget=forms.TextInput(attrs={'class': "input-lg"}))
    code = forms.CharField(label='Printer Code', max_length=10,widget=forms.TextInput(attrs={'class': "input-lg"}))    
    description = forms.CharField(label='Printer Description')
    
class OrthoModoJobForm(forms.ModelForm):
    orthotrac_analysis_notes = forms.CharField(label='Orthotrac ANalysis Notes')
    
class LabItemForm(forms.ModelForm):
    is_blocked = forms.CharField(label='Printer Name', max_length=200,widget=forms.TextInput(attrs={'class': "input-lg"}))

    

templates/orthomodoweb/printer/printer_add_form.html
{% extends 'orthomodoweb/base.html' %}
{% block content %}
	
	<div class="form_header">ADD New Printer</div>
	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
	<div class = "formcontainer_f">	
		<form action="" method="post">
			{% csrf_token %}
			
			<i class="fa fa-address-card-o" aria-hidden="true"></i> <label for="id_code">CODE*:</label>	
			<br />
			<input type="text" name="code" id="id_code" maxlength="200" placeholder = "Code" value = '{{ printer.code }}'>
			<br />
			<i class="fa fa-print" aria-hidden="true"></i> <label for="id_name">NAME*:</label>	
			<br />
			<input type="text" name="name" id="id_name" maxlength="200" placeholder = "Name" value = '{{ printer.name }}'>
			<br />
			<i class="fa fa-sticky-note-o" aria-hidden="true"></i> <label for="id_description">DESCRIPTION:</label>	
			<br />
			<textarea  rows="5" cols="120" name="description" id="id_description" placeholder = "Description">{{ printer.description }}</textarea>
			<br />			
			<input class="button"type="submit" value="SAVE" />
		 </form>
		
	</div>	

{% endblock %}

templates/orthomodoweb/printer/printer_confirm_delete.html
{% extends 'orthomodoweb/base.html' %}
{% block content %}
	<h1>Printer: DELETE</h1>
	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

	<form action="" method="post">{% csrf_token %}
		<p>Are you sure you want to delete "{{ object }}"?</p>
		<input type="submit" value="Confirm" />
	</form>
{% endblock %}

templates/orthomodoweb/printer/printer_form.html
{% extends 'orthomodoweb/base.html' %}
{% block content %}
	
	<div class="form_header">Printer: {{ printer.name }}</div>
	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
	<div class = "formcontainer_f">	
		<form action="" method="post">
			{% csrf_token %}
			
			<i class="fa fa-address-card-o" aria-hidden="true"></i> <label for="id_code">CODE*:</label>	
			<br />
			<input type="text" name="code" id="id_code" maxlength="200" placeholder = "Code" value = '{{ printer.code }}'>
			<br />
			<i class="fa fa-print" aria-hidden="true"></i> <label for="id_name">NAME*:</label>	
			<br />
			<input type="text" name="name" id="id_name" maxlength="200" placeholder = "Name" value = '{{ printer.name }}'>
			<br />
			<i class="fa fa-sticky-note-o" aria-hidden="true"></i> <label for="id_description">DESCRIPTION:</label>	
			<br />
			<textarea  rows="5" cols="120" name="description" id="id_description" placeholder = "Description">{{ printer.description }}</textarea>
			<br />			
			<input class="button"type="submit" value="SAVE" />
		 </form>
		
	</div>	
	<div class="datatable">
	<div class = "datatable_header">Printer Jobs</div>
	
		<table>
		<tr>
				<th colspan="5" class="header_group_1">Basic Info</th>
				<th colspan="2" class="thickborderleft header_group_2">Orthotrac Analysis</th>
				<th colspan="4" class="thickborderleft header_group_3">3D Printed Model</th>
				<th colspan="2" class="thickborderleft header_group_3">Plaster Model</th>
				<th colspan="1" class="thickborderleft header_group_3">Use For</th>
				<th colspan="2" class="thickborderleft header_group_4">Lab Items</th>
				<th colspan="5" class="thickborderleft header_group_5">Collection</th>
				<th colspan="2" class="thickborderleft header_group_6">Flag Status</th>
				<th colspan="2" class="thickborderleft header_group_1">Last Updated</th>
			</tr>
			<tr>
				<th>ID</th>
				<th>Model type</th>
				<th>Scan&nbsp;Date</th>
				<th>Patient</th>
				<th>Clinician</th>				
				<th class="thickborderleft">Done?</th>
				<th>Notes</th>
				<th class="thickborderleft">Printer</th>
				<th>STL file?</th>
				<th>Printed?</th>
				<th>Print Date</th>
				<th class="thickborderleft">Poured?</th>
				<th>Pour Date</th>
				<th class="thickborderleft">&nbsp;&nbsp;&nbsp;&nbsp;Use&nbsp;&nbsp;&nbsp;&nbsp;</th>
				<th class="thickborderleft">Qty</th>
				<th>&nbsp;Item&nbsp;Details&nbsp;&nbsp;</th>
				<th class="thickborderleft">Type</th>
				<th>Planned Date</th>
				<th>Time</th>
				<th>Notes</th>
				<th>Collected?</th>
				<th class="thickborderleft">Status</th>
				<th >Notes</th>
				<th >By</th>
				<th >When</th>
			</tr>
		{% if printer.orthomodojob_set %}
			{% for orthomodojob in printer.orthomodojob_set.all|dictsortreversed:"id"  %}
				<tr>			
				<td><a href="{% url 'orthomodoweb:orthomodojob-update' orthomodojob.id %}">OMJOB_{{ orthomodojob.id }}</a></td>
				<td>{{ orthomodojob.model_type }}</td>
				<td>{{ orthomodojob.scan_date|date:"y-m-d" }}</td>
				<td><a href="{% url 'orthomodoweb:patient-update' orthomodojob.patient.id %}">{{orthomodojob.patient.code}}: {{ orthomodojob.patient.name }}</a></td>
				<td>{% if orthomodojob.clinician %}<a href="{% url 'orthomodoweb:clinician-update' orthomodojob.clinician.id %}">{{ orthomodojob.clinician.name }}</a>{% endif %}</td> 			
				<td class="thickborderleft">{{ orthomodojob.orthotrac_analysis_done|yesno:"Yes,No" }}</td>
				<td class="compact_table_cell_normal_font">{{ orthomodojob.orthotrac_analysis_notes|truncatechars:30 }}</td>
				<td class="thickborderleft">{% if orthomodojob.printer %}<a href="{% url 'orthomodoweb:printer-update' orthomodojob.printer.id %}">{{ orthomodojob.printer.name }}</a>{% endif %}</td>
				<td>{{ orthomodojob.is_stl_file_prepared|yesno:"Yes,No" }}</td>
				<td>{{ orthomodojob.is_printed|yesno:"Yes,No" }}</td>
				<td>{{ orthomodojob.print_date|date:"y-m-d" }}</td>
				<td class="thickborderleft">{{ orthomodojob.is_poured|yesno:"Yes,No" }}</td>
				<td>{{ orthomodojob.poured_date|date:"y-m-d" }}</td>
				<td class="thickborderleft">{{ orthomodojob.created_model_use.code }}</td>
				<td class="thickborderleft">{{ orthomodojob.labitem_set.count }}</td>
				<td> {% for lab_item in orthomodojob.labitem_set.all  %}
						
							<span class="compact_table_cell">
							{{lab_item.lab_item_type.code}}
							<span style="color: #f5f2f2;background-color: #000000;">{{lab_item.lab_item_material.code}}</span>
							{{lab_item.is_blocked|yesno:"B,U"}}
							<span style="color:#ec3c3c">{{lab_item.is_made|yesno:"M,U"}}
							</span>{{lab_item.made_date|date:"m-d"}}<br />
							</span>
							
					{% endfor %}	</td>
				<td class="thickborderleft">{% if orthomodojob.collection_type %}<a href="{% url 'orthomodoweb:collectiontype-update' orthomodojob.collection_type.id %}">{{ orthomodojob.collection_type.name }}</a>{% endif %}</td>
				<td>{{orthomodojob.planned_collection_date|date:"y-m-d"}}</td>
				<td>{{orthomodojob.planned_collection_time}}</td>
				<td class="compact_table_cell_normal_font">{{orthomodojob.collection_notes|truncatechars:30}}</td>			
				<td>{{orthomodojob.is_collected|yesno:"Yes,No"}}</td>
				<td class="thickborderleft status{% if orthomodojob.flagged %}_flagged{% endif %}">{{ orthomodojob.flagged|yesno:"FLAGGED,normal" }}</td>
				<td class="compact_table_cell_normal_font status{% if orthomodojob.flagged %}_flagged{% endif %}">{{ orthomodojob.flag_status_note|truncatechars:30 }}</td>
				<td class="compact_table_cell_normal_font">{{ orthomodojob.last_updated_by }}</td>
				<td class="compact_table_cell_normal_font">{{ orthomodojob.date_updated|date:'y-m-d (H:i)' }}</td>
				</tr>
			{% endfor %}
			</table>	
		
		{% else %}
			</table>
			<p class="emptylist">No OrthoModoJobs found for this printer.</p>
		{% endif %}
	</div>
	<div class="bottom_action_links">
		<a class="button" href="{% url 'orthomodoweb:printer-add' %}">Add NEW Printer</a>
		<!-- <a class= "button_red" href="{% url 'orthomodoweb:printer-delete' printer.id%}">Delete this Printer</a>			 -->
	</div>

{% endblock %}

templates/orthomodoweb/printer/printer_list.html
{% extends 'orthomodoweb/base.html' %}
{% block content %}
	<div class="standard_page_container">
		<div class="standard_page_container_header">PRINTERS: {{ total_printers }}</div>
	
		{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
		
		{% if object_list  %}			
			<table>
				<tr>					
					<th class="header_group_2">ID</th>		
					<th class="header_group_2">Code</th>		
					<th class="header_group_2">Name</th>								
					<th class="header_group_2">Description</th>
				</tr>				
			{% for printer in object_list  %}
				<tr>				
					<td><a href="{% url 'orthomodoweb:printer-update' printer.id %}">Printer {{ printer.id }}</a> </td>
					<td>{{ printer.code }}</td>		
					<td>{{ printer.name }}</td>
					<td>{{ printer.description }}</td>
					</li>
				</tr>
			{% endfor %}
				
			</table>
		{% else %}
			<p>No Printers found.</p>
		{% endif %}
		 <p>
		 <a class = "button" href="{% url 'orthomodoweb:printer-add' %}">Add Printer</a>
		</p>
	</div>

{% endblock %}